baseurl = "//sysadmin-galicia.github.io/"
languageCode = "en-us"
title = "sysadmin@galicia"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]
	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "sysadmin@galicia"
	description = "sysadmin@galicia"

	# The path must be relative to the static folder
	favicon = "favicon.ico"

	# Navigation
	[params.navigation]
		brand = ""

		[params.navigation.links]
			about     = "Que es Sysadmin@Galicia"
			services  = "Donde encontrarnos"
			portfolio = "Portfolio"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Sysadmin@Galicia"
		subtitle   = "<p/>"
		buttonText = "Entrar"


	# About section
	[params.about]
		headline    = "Que es Sysadmin@Galicia"
		description = "Este es un grupo de y para sysadmins. Si eres de los que sufren los sistemas, si tienes hordas de usuarios a los que mantienes a raya a diario, si sabes cuánto tiempo tarda en reconstruirse un RAID5 de 10 discos, si conoces las sesiones de HTTP con tan sólo ver un tcpdump, si planificas las navidades como cosas que podrás hacer sin interferencia de los usuarios y si tus vacaciones son en... ¿vacaciones, qué es eso? Entonces: Este grupo es para ti. Dentro de este grupo organizamos reuniones, charlas y formación interesante, además de servir como un foro en el que buscar ayuda local para solucionar cualquier problema de administración de sistemas."


	# Service section
	[params.services]
		headline = "Puedes encontrarnos en...."
      [[params.services.list]]
        icon = "fa-meetup"
        title = "meetup"
        description= "[#Sysadmin@Galicia](https://www.meetup.com/Sysadmin-Galicia)"

      [[params.services.list]]
        icon = "fa-twitter"
        title = "twitter"
        description = "[@sysadmingalicia](https://twitter.com/sysadmingalicia)"

	# Contact section
	[params.contact]
		headline = "Kaleido coworking"
		description = "Los meetup de Sysadmin@Galicia se realizan en un espacio cedido por Kaleido Coworking"
		phone = "886 44 07 15"
		email = "coworking@kaleidologistics.com"

	# Google Maps section
	[params.location]
		latitude  = "42.2373317"
	 	longitude = "-8.7200455"
	 	maps_api_key = "AIzaSyCUYwju1dFFp_v3oJyR5xbsezIi3IFbVdM"
